{% set version = "0.0.5" %}

package:
  name: pymodsecurity
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pymodsecurity/pymodsecurity-{{ version }}.tar.gz
  sha256: c597d1ba95fad4fcb62a66f82a60119cdf36290c65f1f236db73f8dce7348600

build:
  number: 0
  skip: true  # [not linux or py<35]
  script:
    - CFLAGS="-I$PREFIX/include -L$PREFIX/lib"
    - {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - modsecurity
    - pybind11 >=2.2
  run:
    - modsecurity
    - python
    # remove this pin once the dependencies are rebuilt
    - icu 58

test:
  imports:
    - ModSecurity

about:
  home: https://github.com/actions-security/pymodsecurity
  summary: Python bindings to libmodsecurity
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - GustavoKatel
