travis:
  secure:
    BINSTAR_TOKEN: F++faBF4FlGJrIMFlavEj9NEigWAWlZbpXW9/j9xFUz7ah/7lot1sMmF01GdSv7K5TKVLZ47nAZDlI1bIfCO0gM3KDTnEVRzzLLkgwtD8AcypUcxmghvIy3ybpB5XnEOm/u1gbrxz1/5zybI2h6XJEVGaRaWmFCyLVPC7kKeMNVV/xk0hQUChwdwpdd5YTUuptuW1LirJFqYk25CoR+aBHp6NXCoMQ7RlbqCRBS+GJgcLpwyAe9/KUNdlJfav4SjQM5OOWBkb3KL3OTiqkwatUMJdFUBaY4oLTRR7nhTsQG6BgFpSRK//2x/q6rYqh+fTkhXGIBE6O3EF3F5MP/5G+nuMBaGNXtaZhdGlN+E5oqXAxvCwLDl3J8A16yB8SBeUXAzf0AsAIijPjawqhrm/b/LXrzZ/535kenzwJTSJScbF9G702SzEI4ANAdpjEEmuTz+g43XaVrjaMjJn7NCc84BRijG64lCtfdDPIEnXlz/U7RF2CxuIiHcsiEF2qR4t7/1wt6X/YBb+0qT0HZd5k1Aq+/yf851A7+aiMwm9mG/Q5KE6cQyzUNZv0jZI96azU57iJzjCiYK5+C9CqX9mRLmSHROmqSZO1KtVO4iOyUxRC58Mv6xNjoz0my4wtmdS41BJ8vggHa6vtc0yxLIHogd7DVx/UBeVYnMAlr6/3g=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
